// ============================================
// NeuroGUARDIAN — Agent Types
// Core type definitions for the multi-agent system
// Version: 5.0.0 | Date: January 2026
// ============================================

import type { z } from 'zod';

// ============================================
// STATE TYPES
// ============================================

/**
 * User state tracked across sessions
 * Enables contextual responses and pending action handling
 */
export interface UserState {
  // === STATIC (rarely changes) ===
  userId: number;
  marketplace: 'WB' | 'Ozon' | 'both' | null;
  hasWbKey: boolean;
  hasOzonKey: boolean;
  hasApiKeys: boolean;
  productsCount: number;
  subscriptionTier: 'free' | 'basic' | 'pro';

  // === DYNAMIC (per session) ===
  currentIntent?: string;

  /** Pending action awaiting user confirmation */
  pendingAction?: {
    type: 'update_price' | 'set_stop_loss' | 'bulk_protect' | 'update_stock';
    productId?: string;
    productIds?: string[];
    params: Record<string, unknown>;
    createdAt: Date;
  };

  /** Awaiting user input (e.g., cost_price after asking) */
  awaitingInput?: {
    type:
      | 'cost_price'
      | 'period'
      | 'product_name'
      | 'min_price'
      | 'confirmation'
      | 'percentage'
      | 'nm_id';
    forProductId?: string;
    question: string;
    createdAt: Date;
  };

  /** Recently mentioned products (for context) */
  lastMentionedProducts: string[];

  /** Last query for context resolution */
  lastQuery?: string;

  // === META ===
  lastActiveAt: Date;
  sessionStartedAt: Date;
  totalQueries: number;
}

/**
 * Conversation message
 */
export interface ChatMessage {
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: Date;
  metadata?: {
    toolsCalled?: string[];
    intent?: string;
  };
}

export type AgentMessage = ChatMessage;

// ============================================
// TOOL TYPES
// ============================================

/**
 * Result returned by any tool execution
 */
export interface ToolResult {
  success: boolean;
  data?: unknown;
  error?: string;
  /** URLs found in the result (for link validation) */
  urls?: string[];
}

/**
 * Tool definition for the registry
 */
export interface ToolDefinition<TArgs = unknown> {
  /** Unique tool name (snake_case) */
  name: string;

  /** Human-readable description for the prompt */
  description: string;

  /** Zod schema for argument validation */
  schema: z.ZodSchema<TArgs>;

  /** Tool category for filtering */
  category: 'read' | 'write' | 'analyze' | 'search';

  /** Whether this tool requires user confirmation before execution */
  requiresConfirmation: boolean;

  /** Example usages for few-shot prompting */
  examples?: string[];

  /** Execute the tool */
  execute: (userId: number, args: TArgs) => Promise<ToolResult>;
}

/**
 * Planned tool call from the Planner phase
 */
export interface PlannedToolCall {
  tool: string;
  args: Record<string, unknown>;
  reason: string;
}

/**
 * Plan generated by the Planner
 */
export interface AgentPlan {
  reasoning: string;
  tools: PlannedToolCall[];
  requiresConfirmation: boolean;
}

// ============================================
// ORCHESTRATOR TYPES
// ============================================

/**
 * Context passed to the orchestrator
 */
export interface OrchestratorContext {
  userId: number;
  userName?: string;
  isFirstContact?: boolean;
  onboardingMode?: boolean;
  /** Force direct tool execution (bypasses planning) */
  directExecution?: {
    tool: string;
    args: Record<string, unknown>;
  };
  /** Marketplace context for the current request */
  marketplace?: 'WB' | 'Ozon' | 'both';
}

/**
 * Result from the orchestrator
 */
export interface OrchestratorResult {
  success: boolean;
  message: string;

  /** Links to include in the response */
  links?: Array<{
    title: string;
    url: string;
    source: string;
  }>;

  /** Actions taken or proposed */
  actions?: Array<{
    type: string;
    summary: string;
    details: Record<string, unknown>;
    affectedCount: number;
  }>;

  /** Additional data payload */
  data?: Record<string, unknown>;

  // === METRICS ===
  planningTimeMs: number;
  executionTimeMs: number;
  answeringTimeMs: number;
  totalTimeMs: number;
  tokensUsed: number;
  toolsCalled: string[];

  // === DEBUG ===
  plan?: AgentPlan;
  toolResults?: ToolResult[];
}

// ============================================
// LLM TYPES
// ============================================

/**
 * LLM provider configuration
 */
export interface LLMProviderConfig {
  name: string;
  url: string;
  apiKey: string;
  model: string;
  supportsStructuredOutput: boolean;
  supportsJsonMode: boolean;
  maxTokens: number;
  timeout: number;
}

/**
 * LLM completion result
 */
export interface LLMCompletionResult {
  content: string;
  tokensUsed: number;
  provider: string;
  latencyMs: number;
}

// ============================================
// MEMORY TYPES
// ============================================

/**
 * Fact stored in long-term memory
 */
export interface MemoryFact {
  id: string;
  userId: number;
  type: 'user_preference' | 'product_info' | 'business_rule' | 'resolved_issue';
  content: string;
  createdAt: Date;
  relevanceScore?: number;
}

/**
 * Memory search result
 */
export interface MemorySearchResult {
  facts: MemoryFact[];
  searchLatencyMs: number;
}
