"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.mapOzonProductToProduct = exports.updateOzonPrice = exports.zeroOzonStock = exports.fetchOzonPrices = exports.fetchOzonProductInfo = exports.fetchOzonProducts = exports.mapWBCardToProduct = exports.updateWBPrice = exports.zeroWBStock = exports.fetchWBPrices = exports.fetchWBCards = exports.hasApiKey = exports.deleteApiKey = exports.getApiKey = exports.storeApiKey = void 0;
var secretManager_1 = require("./secretManager");
Object.defineProperty(exports, "storeApiKey", { enumerable: true, get: function () { return secretManager_1.storeApiKey; } });
Object.defineProperty(exports, "getApiKey", { enumerable: true, get: function () { return secretManager_1.getApiKey; } });
Object.defineProperty(exports, "deleteApiKey", { enumerable: true, get: function () { return secretManager_1.deleteApiKey; } });
Object.defineProperty(exports, "hasApiKey", { enumerable: true, get: function () { return secretManager_1.hasApiKey; } });
var wbFetcher_1 = require("./wbFetcher");
Object.defineProperty(exports, "fetchWBCards", { enumerable: true, get: function () { return wbFetcher_1.fetchWBCards; } });
Object.defineProperty(exports, "fetchWBPrices", { enumerable: true, get: function () { return wbFetcher_1.fetchWBPrices; } });
Object.defineProperty(exports, "zeroWBStock", { enumerable: true, get: function () { return wbFetcher_1.zeroWBStock; } });
Object.defineProperty(exports, "updateWBPrice", { enumerable: true, get: function () { return wbFetcher_1.updateWBPrice; } });
Object.defineProperty(exports, "mapWBCardToProduct", { enumerable: true, get: function () { return wbFetcher_1.mapWBCardToProduct; } });
var ozonFetcher_1 = require("./ozonFetcher");
Object.defineProperty(exports, "fetchOzonProducts", { enumerable: true, get: function () { return ozonFetcher_1.fetchOzonProducts; } });
Object.defineProperty(exports, "fetchOzonProductInfo", { enumerable: true, get: function () { return ozonFetcher_1.fetchOzonProductInfo; } });
Object.defineProperty(exports, "fetchOzonPrices", { enumerable: true, get: function () { return ozonFetcher_1.fetchOzonPrices; } });
Object.defineProperty(exports, "zeroOzonStock", { enumerable: true, get: function () { return ozonFetcher_1.zeroOzonStock; } });
Object.defineProperty(exports, "updateOzonPrice", { enumerable: true, get: function () { return ozonFetcher_1.updateOzonPrice; } });
Object.defineProperty(exports, "mapOzonProductToProduct", { enumerable: true, get: function () { return ozonFetcher_1.mapOzonProductToProduct; } });
//# sourceMappingURL=index.js.map