import { z } from 'zod';
export declare const SubscriptionPlan: z.ZodEnum<["trial", "basic", "pro", "enterprise"]>;
export type SubscriptionPlan = z.infer<typeof SubscriptionPlan>;
export declare const PLAN_LIMITS: {
    readonly trial: {
        readonly maxProducts: 10;
        readonly checkIntervalMinutes: 15;
        readonly defenseModes: readonly ["zero_stock"];
        readonly alertChannels: readonly ["telegram"];
        readonly supportPriority: "low";
        readonly durationDays: 7;
        readonly price: 0;
    };
    readonly basic: {
        readonly maxProducts: 100;
        readonly checkIntervalMinutes: 5;
        readonly defenseModes: readonly ["zero_stock"];
        readonly alertChannels: readonly ["telegram"];
        readonly supportPriority: "normal";
        readonly durationDays: 30;
        readonly price: 990;
    };
    readonly pro: {
        readonly maxProducts: 1000;
        readonly checkIntervalMinutes: 2;
        readonly defenseModes: readonly ["zero_stock", "price_correction"];
        readonly alertChannels: readonly ["telegram", "email"];
        readonly supportPriority: "high";
        readonly durationDays: 30;
        readonly price: 1990;
    };
    readonly enterprise: {
        readonly maxProducts: -1;
        readonly checkIntervalMinutes: 1;
        readonly defenseModes: readonly ["zero_stock", "price_correction"];
        readonly alertChannels: readonly ["telegram", "email", "webhook"];
        readonly supportPriority: "critical";
        readonly durationDays: 365;
        readonly price: 19990;
    };
};
export declare const UserSchema: z.ZodObject<{
    telegramId: z.ZodNumber;
    username: z.ZodNullable<z.ZodString>;
    firstName: z.ZodString;
    lastName: z.ZodNullable<z.ZodString>;
    photoUrl: z.ZodNullable<z.ZodString>;
    languageCode: z.ZodDefault<z.ZodString>;
    subscriptionPlan: z.ZodDefault<z.ZodEnum<["trial", "basic", "pro", "enterprise"]>>;
    subscriptionActive: z.ZodDefault<z.ZodBoolean>;
    subscriptionStartedAt: z.ZodNullable<z.ZodDate>;
    subscriptionExpiresAt: z.ZodNullable<z.ZodDate>;
    autoRenew: z.ZodDefault<z.ZodBoolean>;
    customerId: z.ZodNullable<z.ZodString>;
    paymentMethodId: z.ZodNullable<z.ZodString>;
    totalPaid: z.ZodDefault<z.ZodNumber>;
    protectionEnabled: z.ZodDefault<z.ZodBoolean>;
    defenseMode: z.ZodDefault<z.ZodEnum<["zero_stock", "price_correction"]>>;
    alertsEnabled: z.ZodDefault<z.ZodBoolean>;
    emailForAlerts: z.ZodNullable<z.ZodString>;
    wbKeyRef: z.ZodNullable<z.ZodString>;
    ozonKeyRef: z.ZodNullable<z.ZodString>;
    ozonClientId: z.ZodNullable<z.ZodString>;
    totalProducts: z.ZodDefault<z.ZodNumber>;
    protectedProducts: z.ZodDefault<z.ZodNumber>;
    triggeredToday: z.ZodDefault<z.ZodNumber>;
    triggeredAllTime: z.ZodDefault<z.ZodNumber>;
    savedAmount: z.ZodDefault<z.ZodNumber>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
    lastActiveAt: z.ZodDate;
    lastCheckedAt: z.ZodNullable<z.ZodDate>;
    betaFeatures: z.ZodDefault<z.ZodBoolean>;
    referralCode: z.ZodNullable<z.ZodString>;
    referredBy: z.ZodNullable<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    updatedAt: Date;
    telegramId: number;
    username: string | null;
    firstName: string;
    lastName: string | null;
    photoUrl: string | null;
    subscriptionActive: boolean;
    subscriptionExpiresAt: Date | null;
    subscriptionPlan: "trial" | "basic" | "pro" | "enterprise";
    protectionEnabled: boolean;
    defenseMode: "zero_stock" | "price_correction";
    wbKeyRef: string | null;
    ozonKeyRef: string | null;
    totalProducts: number;
    triggeredToday: number;
    savedAmount: number;
    createdAt: Date;
    lastActiveAt: Date;
    lastCheckedAt: Date | null;
    ozonClientId: string | null;
    languageCode: string;
    subscriptionStartedAt: Date | null;
    autoRenew: boolean;
    customerId: string | null;
    paymentMethodId: string | null;
    totalPaid: number;
    alertsEnabled: boolean;
    emailForAlerts: string | null;
    protectedProducts: number;
    triggeredAllTime: number;
    betaFeatures: boolean;
    referralCode: string | null;
    referredBy: number | null;
}, {
    updatedAt: Date;
    telegramId: number;
    username: string | null;
    firstName: string;
    lastName: string | null;
    photoUrl: string | null;
    subscriptionExpiresAt: Date | null;
    wbKeyRef: string | null;
    ozonKeyRef: string | null;
    createdAt: Date;
    lastActiveAt: Date;
    lastCheckedAt: Date | null;
    ozonClientId: string | null;
    subscriptionStartedAt: Date | null;
    customerId: string | null;
    paymentMethodId: string | null;
    emailForAlerts: string | null;
    referralCode: string | null;
    referredBy: number | null;
    subscriptionActive?: boolean | undefined;
    subscriptionPlan?: "trial" | "basic" | "pro" | "enterprise" | undefined;
    protectionEnabled?: boolean | undefined;
    defenseMode?: "zero_stock" | "price_correction" | undefined;
    totalProducts?: number | undefined;
    triggeredToday?: number | undefined;
    savedAmount?: number | undefined;
    languageCode?: string | undefined;
    autoRenew?: boolean | undefined;
    totalPaid?: number | undefined;
    alertsEnabled?: boolean | undefined;
    protectedProducts?: number | undefined;
    triggeredAllTime?: number | undefined;
    betaFeatures?: boolean | undefined;
}>;
export type User = z.infer<typeof UserSchema>;
export declare const ProductSchema: z.ZodObject<{
    productId: z.ZodString;
    userId: z.ZodNumber;
    marketplace: z.ZodEnum<["WB", "Ozon"]>;
    nmId: z.ZodNullable<z.ZodNumber>;
    offerId: z.ZodNullable<z.ZodString>;
    title: z.ZodString;
    vendorCode: z.ZodString;
    imageUrl: z.ZodNullable<z.ZodString>;
    category: z.ZodNullable<z.ZodString>;
    brand: z.ZodNullable<z.ZodString>;
    currentPrice: z.ZodNumber;
    minPrice: z.ZodDefault<z.ZodNumber>;
    originalPrice: z.ZodNullable<z.ZodNumber>;
    stock: z.ZodDefault<z.ZodNumber>;
    warehouseId: z.ZodNullable<z.ZodNumber>;
    status: z.ZodDefault<z.ZodEnum<["active", "protected", "triggered", "paused", "error"]>>;
    lastTriggeredAt: z.ZodNullable<z.ZodDate>;
    lastCheckedAt: z.ZodNullable<z.ZodDate>;
    errorMessage: z.ZodNullable<z.ZodString>;
    triggerCount: z.ZodDefault<z.ZodNumber>;
    savedAmount: z.ZodDefault<z.ZodNumber>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    status: "active" | "protected" | "triggered" | "error" | "paused";
    vendorCode: string;
    brand: string | null;
    title: string;
    updatedAt: Date;
    nmId: number | null;
    warehouseId: number | null;
    stock: number;
    savedAmount: number;
    createdAt: Date;
    userId: number;
    productId: string;
    offerId: string | null;
    imageUrl: string | null;
    category: string | null;
    currentPrice: number;
    minPrice: number;
    originalPrice: number | null;
    marketplace: "WB" | "Ozon";
    lastCheckedAt: Date | null;
    lastTriggeredAt: Date | null;
    errorMessage: string | null;
    triggerCount: number;
}, {
    vendorCode: string;
    brand: string | null;
    title: string;
    updatedAt: Date;
    nmId: number | null;
    warehouseId: number | null;
    createdAt: Date;
    userId: number;
    productId: string;
    offerId: string | null;
    imageUrl: string | null;
    category: string | null;
    currentPrice: number;
    originalPrice: number | null;
    marketplace: "WB" | "Ozon";
    lastCheckedAt: Date | null;
    lastTriggeredAt: Date | null;
    errorMessage: string | null;
    status?: "active" | "protected" | "triggered" | "error" | "paused" | undefined;
    stock?: number | undefined;
    savedAmount?: number | undefined;
    minPrice?: number | undefined;
    triggerCount?: number | undefined;
}>;
export type Product = z.infer<typeof ProductSchema>;
export declare const TransactionSchema: z.ZodObject<{
    id: z.ZodString;
    userId: z.ZodNumber;
    type: z.ZodEnum<["subscription", "refund", "bonus"]>;
    status: z.ZodEnum<["pending", "succeeded", "failed", "refunded", "canceled"]>;
    amount: z.ZodNumber;
    currency: z.ZodDefault<z.ZodString>;
    planId: z.ZodNullable<z.ZodEnum<["trial", "basic", "pro", "enterprise"]>>;
    periodDays: z.ZodNullable<z.ZodNumber>;
    provider: z.ZodEnum<["yookassa", "cloudpayments", "telegram", "manual"]>;
    externalId: z.ZodNullable<z.ZodString>;
    paymentMethodType: z.ZodNullable<z.ZodString>;
    description: z.ZodNullable<z.ZodString>;
    metadata: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodAny>>;
    createdAt: z.ZodDate;
    paidAt: z.ZodNullable<z.ZodDate>;
    refundedAt: z.ZodNullable<z.ZodDate>;
}, "strip", z.ZodTypeAny, {
    type: "subscription" | "refund" | "bonus";
    status: "failed" | "refunded" | "pending" | "succeeded" | "canceled";
    amount: number;
    id: string;
    createdAt: Date;
    userId: number;
    metadata: Record<string, any>;
    currency: string;
    description: string | null;
    planId: "trial" | "basic" | "pro" | "enterprise" | null;
    periodDays: number | null;
    provider: "telegram" | "yookassa" | "cloudpayments" | "manual";
    externalId: string | null;
    paymentMethodType: string | null;
    paidAt: Date | null;
    refundedAt: Date | null;
}, {
    type: "subscription" | "refund" | "bonus";
    status: "failed" | "refunded" | "pending" | "succeeded" | "canceled";
    amount: number;
    id: string;
    createdAt: Date;
    userId: number;
    description: string | null;
    planId: "trial" | "basic" | "pro" | "enterprise" | null;
    periodDays: number | null;
    provider: "telegram" | "yookassa" | "cloudpayments" | "manual";
    externalId: string | null;
    paymentMethodType: string | null;
    paidAt: Date | null;
    refundedAt: Date | null;
    metadata?: Record<string, any> | undefined;
    currency?: string | undefined;
}>;
export type Transaction = z.infer<typeof TransactionSchema>;
export declare const LogEntrySchema: z.ZodObject<{
    id: z.ZodString;
    userId: z.ZodNumber;
    type: z.ZodEnum<["defense_triggered", "price_restored", "stock_zeroed", "api_connected", "api_error", "sync_completed", "subscription_activated", "subscription_expired", "payment_received", "payment_failed", "settings_changed", "error", "info"]>;
    title: z.ZodString;
    message: z.ZodString;
    productId: z.ZodNullable<z.ZodString>;
    transactionId: z.ZodNullable<z.ZodString>;
    metadata: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodAny>>;
    read: z.ZodDefault<z.ZodBoolean>;
    createdAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    message: string;
    type: "defense_triggered" | "error" | "info" | "price_restored" | "stock_zeroed" | "api_connected" | "api_error" | "sync_completed" | "subscription_activated" | "subscription_expired" | "payment_received" | "payment_failed" | "settings_changed";
    title: string;
    id: string;
    createdAt: Date;
    userId: number;
    productId: string | null;
    metadata: Record<string, any>;
    transactionId: string | null;
    read: boolean;
}, {
    message: string;
    type: "defense_triggered" | "error" | "info" | "price_restored" | "stock_zeroed" | "api_connected" | "api_error" | "sync_completed" | "subscription_activated" | "subscription_expired" | "payment_received" | "payment_failed" | "settings_changed";
    title: string;
    id: string;
    createdAt: Date;
    userId: number;
    productId: string | null;
    transactionId: string | null;
    metadata?: Record<string, any> | undefined;
    read?: boolean | undefined;
}>;
export type LogEntry = z.infer<typeof LogEntrySchema>;
export declare const ReferralSchema: z.ZodObject<{
    code: z.ZodString;
    ownerId: z.ZodNumber;
    totalReferrals: z.ZodDefault<z.ZodNumber>;
    activeReferrals: z.ZodDefault<z.ZodNumber>;
    totalEarned: z.ZodDefault<z.ZodNumber>;
    commissionPercent: z.ZodDefault<z.ZodNumber>;
    createdAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    code: string;
    createdAt: Date;
    ownerId: number;
    totalReferrals: number;
    activeReferrals: number;
    totalEarned: number;
    commissionPercent: number;
}, {
    code: string;
    createdAt: Date;
    ownerId: number;
    totalReferrals?: number | undefined;
    activeReferrals?: number | undefined;
    totalEarned?: number | undefined;
    commissionPercent?: number | undefined;
}>;
export type Referral = z.infer<typeof ReferralSchema>;
export declare const PromoCodeSchema: z.ZodObject<{
    code: z.ZodString;
    discountType: z.ZodEnum<["percent", "fixed"]>;
    discountValue: z.ZodNumber;
    maxUses: z.ZodNullable<z.ZodNumber>;
    usedCount: z.ZodDefault<z.ZodNumber>;
    validFrom: z.ZodDate;
    validUntil: z.ZodNullable<z.ZodDate>;
    planRestrictions: z.ZodNullable<z.ZodArray<z.ZodEnum<["trial", "basic", "pro", "enterprise"]>, "many">>;
    newUsersOnly: z.ZodDefault<z.ZodBoolean>;
    createdBy: z.ZodString;
    createdAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    code: string;
    createdAt: Date;
    discountType: "fixed" | "percent";
    discountValue: number;
    maxUses: number | null;
    usedCount: number;
    validFrom: Date;
    validUntil: Date | null;
    planRestrictions: ("trial" | "basic" | "pro" | "enterprise")[] | null;
    newUsersOnly: boolean;
    createdBy: string;
}, {
    code: string;
    createdAt: Date;
    discountType: "fixed" | "percent";
    discountValue: number;
    maxUses: number | null;
    validFrom: Date;
    validUntil: Date | null;
    planRestrictions: ("trial" | "basic" | "pro" | "enterprise")[] | null;
    createdBy: string;
    usedCount?: number | undefined;
    newUsersOnly?: boolean | undefined;
}>;
export type PromoCode = z.infer<typeof PromoCodeSchema>;
export declare function checkPlanLimits(user: User): {
    canAddProducts: boolean;
    canUseDefenseMode: (mode: string) => boolean;
    remainingProducts: number;
    checkInterval: number;
};
export declare function isSubscriptionActive(user: User): boolean;
export declare function getDaysUntilExpiry(user: User): number | null;
//# sourceMappingURL=models.d.ts.map